name: UnderwaterFFA
version: '${project.version}'
main: me.gram.underwaterffa.UnderwaterFFA
api-version: 1.19

commands:
  start:
    description: start the UnderwaterFFA minigame
  stop:
    description: stop the UnderwaterFFA minigame
  v:
    description: go invisible
  spawnpoint:
    description: set red spawn
  blue:
    description: set spawn point for blue
  red:
    description: set spawn point for red
  gametools:
    description: get FFA minigame setup tools
  test:
    description: ignore this